# Generated by Django 4.2.4 on 2023-09-01 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='brand_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sub_category',
            new_name='product_title',
        ),
    ]
