# Generated by Django 4.2.4 on 2023-09-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_product_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
