# Generated by Django 4.2.4 on 2023-09-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_product_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='add_info',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_desc',
            field=models.CharField(default='', max_length=300),
        ),
    ]
