# Generated by Django 4.2.4 on 2023-09-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_product_add_info_product_sub_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='add_info',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_desc',
            field=models.CharField(default='', max_length=600),
        ),
    ]
