# Generated by Django 4.2.4 on 2023-09-01 15:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_product_add_info_alter_product_sub_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='add_info',
            field=ckeditor.fields.RichTextField(null='true'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_desc',
            field=ckeditor.fields.RichTextField(null='true'),
        ),
    ]
