# Generated by Django 4.2.4 on 2023-09-07 08:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_product_add_info_alter_product_sub_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=ckeditor.fields.RichTextField(null='true'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
