# Generated by Django 4.2.4 on 2023-09-11 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0011_rename_product_name_product_name_alter_product_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=112)),
                ('last_name', models.CharField(max_length=112)),
                ('email', models.EmailField(max_length=102)),
                ('message', models.TextField()),
                ('address', models.TextField()),
                ('phoneNo', models.IntegerField(max_length=12)),
                ('houseno', models.IntegerField(max_length=12)),
                ('postcode', models.IntegerField(max_length=12)),
                ('amount', models.CharField(max_length=12)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=212)),
                ('image', models.ImageField(upload_to='static/images/order_img')),
                ('quantity', models.EmailField(max_length=102)),
                ('price', models.CharField(max_length=50)),
                ('total', models.CharField(max_length=1000)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.order')),
            ],
        ),
    ]
