# Generated by Django 4.2.4 on 2023-09-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='houseno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='phoneNo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.IntegerField(),
        ),
    ]
