# Generated by Django 4.2.4 on 2023-09-11 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_order_paid_order_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='message',
        ),
    ]
