# Generated by Django 4.2.4 on 2023-09-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_alter_order_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='houseno',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.CharField(max_length=50),
        ),
    ]
